name: Frontend Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-pipeline.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      working-directory: frontend
      run: npm install

    - name: Create .env file
      working-directory: frontend
      run: |
        echo "VITE_COGNITO_AUTHORITY=${{ vars.VITE_COGNITO_AUTHORITY }}" >> .env
        echo "VITE_COGNITO_CLIENT_ID=${{ secrets.VITE_COGNITO_CLIENT_ID }}" >> .env
        echo "VITE_COGNITO_REDIRECT_URI=${{ vars.VITE_COGNITO_REDIRECT_URI }}" >> .env
        echo "VITE_COGNITO_POST_LOGOUT_REDIRECT_URI=${{ vars.VITE_COGNITO_POST_LOGOUT_REDIRECT_URI }}" >> .env
        echo "VITE_COGNITO_RESPONSE_TYPE=${{ vars.VITE_COGNITO_RESPONSE_TYPE }}" >> .env
        echo "VITE_COGNITO_SCOPE=${{ vars.VITE_COGNITO_SCOPE }}" >> .env
        echo "VITE_COGNITO_DOMAIN=${{ vars.VITE_COGNITO_DOMAIN }}" >> .env
        echo "VITE_COGNITO_LOGOUT_URI=${{ vars.VITE_COGNITO_LOGOUT_URI }}" >> .env
        echo "VITE_API_GATEWAY_ENDPOINT=${{ vars.VITE_API_GATEWAY_ENDPOINT }}" >> .env

    - name: Build React app
      working-directory: frontend
      run: npm run build

    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@v0.5.1
      with:
        args: --delete
      env:
        AWS_S3_BUCKET: ${{ vars.MANGOS_S3_STATIC_WEBSITE_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: sa-east-1
        SOURCE_DIR: frontent/dist